#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#### AUTOSTART ####
sxhkd &
picom &
# polybar example &
~/.config/polybar/cuts/scripts/updates.sh &
~/.config/polybar/launch.sh --cuts &
nitrogen --restore &
flameshot &
nm-applet &
wmname LG3D &
blueman-applet &
xscreensaver &
# ~/.screenlayout/NewSL.sh &

setxkbmap -model pc105 -layout us,ara -variant ,qwerty_digits -option grp:win_space_toggle &


bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9

# bspc monitor HDMI1 -d 1 2 3

#### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width                  2
bspc config window_gap                    10
bspc config top_padding                   0
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            false
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		      "#666666"
bspc config active_border_color	              "#666666"
bspc config focused_border_color	      "#cccccc"
bspc config presel_feedback_color	      "#888888"
bspc config urgent_border_color 	      "#dd2727"

# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_eDP1)



bspc rule -a Gimp desktop='^8' state=tiled follow=on
bspc rule -a google-chrome-stable desktop='^2'
# bspc rule -a code desktop='^3'
# bspc rule -a codeblocks desktop='^3'
# bspc rule -a eclipse desktop='^3'
bspc rule -a qbittorrent desktop='^9'
# bspc rule -a thunar desktop='^3'





